### ISSUE TITLE
Allow user avatar in login screen

### ISSUE THREAD

**Issue by spottech** [budgie-remix/budgie-remix-lightdm-theme#1]
change show-language-selector=false by show-language-selector=true in 99_budgie-remix.conf

**Comment by spottech** [comment]
oups
it's user-image not language selector
I just saw that I was wrong in my copy/paste

**Comment by fossfreedom** [comment]
Both myself and @HEXcube are looking to swap to the unity-greeter

![](https://cloud.githubusercontent.com/assets/3755396/14540769/6834505c-02a4-11e6-8f99-7e613dd5996c.png)

**Comment by RohanVilloth** [comment]
@spottech Yeah, like @fossfreedom mentioned we're switching from the default GTK Greeter to **Unity Greeter** for offering a more beautiful user interface. Unity Greeter trades some traditional login screen elements (including user avatar) for a sleek look. :smiley: So unfortunately, user avatars aren't possible on Unity Greeter at the moment. But, we'll consider this feature once we implement our own theme for LightDM in a future release cycle. :relaxed:

**Comment by fossfreedom** [comment]
close - we'll consider all of this with the new greeter

**Comment by ozwaldorf** [comment]
@spottech not to necro a thread but this is an option in the new lightdm greeter we're working on
