### ISSUE TITLE
Wrong cursor theme (Breeze) gets set on LightDM Login Screen

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-lightdm-theme#11]
our default on the desktop is DMZ-White - on the lightdm login screen it defaults to breeze - probably this is because we now package both breeze and dmz-cursors - and maybe the lastone installed wins.

Need to look at the greeter config file and add the cursor override - assuming there is such a thing.

**Comment by RohanVilloth** [comment]
In my opinion, **Breeze** is definitely a better theme than **DMZ-White** . Any possibility for a bug turned feature? :grin:

**Comment by fossfreedom** [comment]
for the moment I've reverted this  - breeze has to be manually installed.
Yeah - a bug report on lightdm-gtk-greeter needs to be raised if its not already. The only way this will be implemented though if someone gets their hands dirty and supply a code-patch.

**Comment by darim92** [comment]
There is a dirty fix for this. Go to /usr/share/icons/default and open index.theme with an editor.

Change Inherits to Inherits=DMZ-White

**Comment by fossfreedom** [comment]
@darim92 many thanks for this - very useful to know.

From a packaging point of view though - have my doubts this would be possible to-do [messing around with a delivered file from another package].  It would be much better to get this fixed correctly in lightdm via a code-patch.  I seemed to remember there was a patch floating around somewhere on the interwebs - no idea of its status though in terms of getting it incorporated into lightdm-gtk-greeter.

**Comment by fossfreedom** [comment]
closing - we've moved on to slick-greeter and breeze looks odd with this.
