### ISSUE TITLE
Change default Icons from Moka to Papirus

### ISSUE THREAD

**Issue by darim92** [budgie-remix/budgie-remix-lightdm-theme#12]
The Papirus Icons look way more polished and fancier than Moka. Also Papirus has more features and options.

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

**Comment by fossfreedom** [comment]
Paprius does not exist in Debian - thus will need to be packaged and uploaded there first before we can consider this.

Given that there is a PPA, we could suggest to add to the "default settings" bit of budgie-welcome a section for users to choose an icon-theme of their choosing - papirus, numix circle, el capitain etc.

**Comment by RohanVilloth** [comment]
@darim92  We already have **Paper** (which's the base for Papirus) available for selection from _Budgie Welcome_. But like @fossfreedom pointed out, we could add Papirus too from their PPA - [Link](https://launchpad.net/~papirus/+archive/ubuntu/papirus), should sufficient user demand arise. If adding Papirus, I'm rooting for splitting the currently offered Material style (Paper icons and Adapta theme) into:

- **Material** (Papirus icons and Adapta theme)
- **Paper** (icons, theme, cursors everything Paper)

**Comment by ozwaldorf** [comment]
I'd say we should stick with the best looking and most polished one. Having too many options would be too overwhelming (Less is more, etc)

If a user prefers a different theme, it really isn't that difficult to install

**Comment by fossfreedom** [comment]
not in the project plans for this.
