### ISSUE TITLE
Add Material wallpaper as one of the defaults

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-lightdm-theme#14]
as per this commit - need to add this wallpaper as to one of this packages defaults - we will be using this in budgie-welcome.

https://github.com/UbuntuBudgie/assets/commit/43c48697e8755d5aac510381ada1ba7277e90a85

**Comment by RohanVilloth** [comment]
Shouldn't this issue be filed against [budgie-wallpapers](https://github.com/UbuntuBudgie/budgie-wallpapers)? :confused: Anyway, now that David pushed the wallpaper to repo (See commit: https://github.com/UbuntuBudgie/budgie-wallpapers/commit/076990e75b1105135e0805cd8a073c65942e01f2), I think this issue should be closed.

**Comment by fossfreedom** [comment]
yep.
