### ISSUE TITLE
modified nm-applet

### ISSUE THREAD

**Issue by spottech** [budgie-remix/budgie-remix-lightdm-theme#2]
the passphrase box does not work again

**Comment by spottech** [comment]
Comfirmed, work great in live mode but not after install

**Comment by spottech** [comment]
(nm-applet:8988): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by fossfreedom** [comment]
resolved with 10.2.8 budgie uplift on 16.04 and 16.10
