### ISSUE TITLE
remix-greeter - blank screen on startup

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-lightdm-theme#7]
with 2.1.4 of lightdm-webkit2-greeter the antegros greeter works just fine on 16.04

the remix greeter gives this picture - i.e. the panel and nothing else:

![screenshot from 2016-09-13 22-39-58](https://cloud.githubusercontent.com/assets/996240/18502420/e8b607bc-7a4e-11e6-992c-a73c5b494862.png)

turning on debug I noticed this in /var/log/lightdm/seat0-greeter.log

file:///usr/share/lightdm-webkit/themes/remix-greeter/javascript/GUI.js:58:38: CONSOLE ERROR ReferenceError: Can't find variable: Config

Any thoughts on this @The5heepDev ?

**Comment by ozwaldorf** [comment]
Fixed in commit 3b8ca9c
Bug was due to missing file 'config.js '
